Repository datosgobes/DCAT-AP-ES, pull requests merged in 2025-03, with the labels that each got.

#15 Versión inicial 1.0.0
  README.en.md
  README.md
  docs/adoc/README.md
  docs/adoc/conventions.adoc
  docs/assets/css/header.css
  docs/assets/css/style.css
  docs/conventions.en.md
  docs/conventions.md
  docs/img/iniciativa_aporta.svg
  docs/index.md
  examples/ttl/A01_Nombre_Catálogo.ttl
  examples/ttl/A02_Nombre_Catálogo_ampliado.ttl
  examples/ttl/Conventions_dataset-dct-spatial-geometry.ttl
  examples/ttl/E1_Catalog_Dataset-DataService-HVD.ttl
  examples/ttl/E2_Catalogo_obligatorias_recomendadas.ttl
  examples/ttl/E6_Dataset_HVD.ttl
  examples/ttl/E8_1_Gestion_identificadores.ttl
  examples/ttl/E8_2_Gestion_identificadores.ttl
  mkdocs.yml
  overrides/dcatapes/conventions_header.html
  overrides/dcatapes/index_header.html
  overrides/main.html
  overrides/partials/header.html
  pyproject.toml
  refs/dev/mkdocs.md
Labels: documentation, enhancement, DCAT-AP-ES, convention

#18 Actualizado worflow de creación de PDFs
  .github/workflows/asciidocpdf.yml
Labels: enhancement

#19 Actualizados workflow de Github Actions
  .github/workflows/asciidocpdf.yml
  .github/workflows/mkdocs.yml
  docs/adoc/resources/theme/datosgobes-theme.yml
  docs/assets/css/codeblocks.css
  docs/assets/css/header.css
  docs/assets/css/style.css
  docs/assets/js/vendor/mermaid.min.js
  docs/examples.md
  docs/faq.en.md
  docs/faq.md
  docs/img/dge_logo.svg
  docs/img/dge_logo_2025.svg
  docs/img/favicon.ico
  docs/img/iniciativa_aporta.svg
  docs/index.en.md
  docs/index.md
  mkdocs.yml
  overrides/.icons/boostrap/spain.svg
  overrides/dcatapes/index_header.html
  refs/dev/versioning.md
  refs/docs/abbreviations.md
Labels: documentation, enhancement

#21 Actualiza nombres de secciones en la navegación y redirecciones en mkdocs.yml para mayor claridad
  mkdocs.yml
Labels: documentation
